### HEALTH CHECK
GET http://localhost:9000/

###
GET http://localhost:9000/api/users
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZGM0N2M4Y2FlZTI1Mzc0N2UwNmExNSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTczMjI4MjA2MywiZXhwIjoxNzMyMjg5MjYzfQ.PypO9T8ifSmkKo4zazK5mvSYW2EzI1Xhotd0APr2nj0

### registering a user 
POST http://localhost:9000/api/users/add
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjVkOTFhOTZiZjg4NDAxNjE5YjYzYSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDk0ODEzOCwiZXhwIjoxNzM0OTU1MzM4fQ.0w9GrMW2l4krIixSRnMyvtOtj1SbKmHq_ry8KOgC1Mk

{
  "name": "simon kamau",
  "email": "simogatuma26@gmail.com",
  "password": "demo123",
  "role": "admin",
  "phone": "+254759717759",
  "photo": "https://res.cloudinary.com/djx5h4cjt/image/upload/v1632216824/avatars/1632216823664.jpg"
 
}

### login
POST http://localhost:9000/api/users/login
Content-Type: application/json

{
  "name": "simon kamau",
  "password": "demo123"
}

### delete a user
DELETE http://localhost:9000/api/users/679b88dcc673b413717f90ef
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZGM0N2M4Y2FlZTI1Mzc0N2UwNmExNSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTczMjE4Mjg3OCwiZXhwIjoxNzMyMTkwMDc4fQ.1oJy1Ljuen7mwQO0yffaJNL9WSAzfr599uywg9Z1Hss

###
GET http://localhost:9000/api/users/679406d6f60c1793f20a2b93
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZGM0N2M4Y2FlZTI1Mzc0N2UwNmExNSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyNTcxNDA0OCwiZXhwIjoxNzI1NzIxMjQ4fQ.Ls8o-D3kX-Gr1RDw2BiNmcpFjF8-hv5V2zdL01DYLaY


### registering a user 
PUT  http://localhost:9000/api/user/679406d6f60c1793f20a2b93
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjVkOTFhOTZiZjg4NDAxNjE5YjYzYSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDk0ODEzOCwiZXhwIjoxNzM0OTU1MzM4fQ.0w9GrMW2l4krIixSRnMyvtOtj1SbKmHq_ry8KOgC1Mk

{
  "name": "simon kamau",
  "email": "simogatuma21@gmail.com",
  "password": "demo123",
  "role": "admin",
  "phone": "+254759717759",
  "photoUrl": "https://images.pexels.com/photos/30379636/pexels-photo-30379636/free-photo-of-woman-in-winter-clothes-enjoying-snowy-forest.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load"
 
}
